name: Increment training
on:  
  push:
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Load enviroment
        run: |
          python3 -m venv my_env
          source my_env/bin/activate
          python3 -m pip install -r requirements.txt
      - name: Train
        run: |
          python3 main.py --summary
        
    
  
