name: Increment training
on:  
  push:
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load enviroment
        run: |
          python3 -m venv my_env
          source my_env/bin/activate
          python3 -m pip install -r requirements.txt
      - name: Train
        run: |
          source my_env/bin/activate
          python3 main.py -m update
          python3 main.py -m inference test.csv
          python3 main.py -m summary
      - name: Saving models
        uses: actions/upload-artifact@v4
        with:
          name: 'models'
          path: './models_*'
      - name: Saving preproc
        uses: actions/upload-artifact@v4
        with:
          name: 'preproc'
          path: './preproc'
      - name: Saving reports
        uses: actions/upload-artifact@v4
        with:
          name: 'reports'
          path: './reports*'
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          echo "my_env" >> .gitignore
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated changes"
          git push
